name: ci

on:
  push:
    branches:
      - 'main'
      - 'build_action'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push v13
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:13.0-arm64"
          push: true
          tags: fbieringer/odoo:13.0-arm64,fbieringer/odoo:13-arm64
          platform: linux/arm64
          cache-to: type=registry,ref=fbieringer/odoo-arm-cache
          cache-from: type=registry,ref=fbieringer/odoo-arm-cache
      -
        name: Build and push v14
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:14.0-arm64"
          push: true
          tags: fbieringer/odoo:14.0-arm64,fbieringer/odoo:14-arm64
          platform: linux/arm64
          cache-to: type=registry,ref=fbieringer/odoo-arm-cache
          cache-from: type=registry,ref=fbieringer/odoo-arm-cache
      -
        name: Build and push v15
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:15.0-arm64"
          push: true
          tags: fbieringer/odoo:15.0-arm64,fbieringer/odoo:15-arm64
          platform: linux/arm64
          cache-to: type=registry,ref=fbieringer/odoo-arm-cache
          cache-from: type=registry,ref=fbieringer/odoo-arm-cache
